CREATE TABLE IF NOT EXISTS SALDO (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    VALOR DECIMAL(10, 2) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS CARTAO (
    ID_CARTAO BIGINT NOT NULL AUTO_INCREMENT,
    NUMERO_CARTAO VARCHAR(16) NOT NULL,
    SENHA VARCHAR(255) NOT NULL,
    SALDO_ID BIGINT NOT NULL,
    PRIMARY KEY (ID_CARTAO),
    CONSTRAINT UK_CARTAO_NUMERO UNIQUE (NUMERO_CARTAO),
    CONSTRAINT UK_CARTAO_SALDO UNIQUE (SALDO_ID),
    CONSTRAINT FK_CARTAO_SALDO FOREIGN KEY (SALDO_ID) REFERENCES SALDO (ID)
);
