CREATE TABLE IF NOT EXISTS CARTAO (
    ID_CARTAO BIGINT NOT NULL AUTO_INCREMENT,
    NUMERO_CARTAO VARCHAR(16) NOT NULL,
    SENHA VARCHAR(255) NOT NULL,
    SALDO DECIMAL(10, 2) NOT NULL,
    PRIMARY KEY (ID_CARTAO),
    CONSTRAINT UK_CARTAO_NUMERO UNIQUE (NUMERO_CARTAO)
);
